#!/bin/sh
#export GMSHLIBS=gmsh-4.9.5-Linux64-sdk/lib
#export LD_LIBRARY_PATH=$GMSHLIBS:$LD_LIBRARY_PATH
# build/bin/dgalerkin $1 $2

#build/bin/dgalerkin doc/2d/square.msh doc/config/config.conf
build/bin/dgalerkin doc/3d/cube.msh doc/config/Cube.conf
